"""The design tokens (`tokens.json`, docs/design-system.md): roles for fonts, colours and space.

A building's UI document names roles only (`"font": "status"`, `"tone": "fire"`). A face maps a
role to what it can draw: the TUI to a text style and a hex colour, the GUI to the design system's
own tokens (`design-system/`, linked here as `system/`): a type style per look, a colour token.

    tokens.FONTS                 # ("title", "heading", "body", "mono", "status", "label", "number")
    tokens.font("status")        # {"about": ..., "tui": ""}
    tokens.color("fire", "office")   # the TUI's hex
    tokens.style("title", "camp")    # "camp-heading": a type style of design-system/tokens.json
    tokens.css_var("fire")           # "--alert": a colour token of design-system/tokens.json
    tokens.roles_css()               # the role classes the GUI's panes wear (.ok-font-status, .ok-tone-fire)
"""
from __future__ import annotations

import functools
import json
from pathlib import Path

PATH = Path(__file__).with_name("tokens.json")
SYSTEM = Path(__file__).with_name("system")       # → design-system/: the GUI's tokens, CSS, fonts, sprites
THEMES = ("camp", "office")


@functools.lru_cache(maxsize=1)
def load() -> dict:
    return json.loads(PATH.read_text(encoding="utf-8"))


@functools.lru_cache(maxsize=1)
def system() -> dict:
    """design-system/tokens.json: the source of truth for every colour and type style the GUI draws."""
    return json.loads((SYSTEM / "tokens.json").read_text(encoding="utf-8"))


def _styles() -> dict[str, dict]:
    """Every type style of the design system by name, with its family (`camp-title` → display, …)."""
    out = {}
    for group in system()["type"]["groups"]:
        for st in group["styles"]:
            out[st["name"]] = {"family": group["family"], **st}
    return out


def _fonts() -> tuple[str, ...]:
    return tuple(load()["fonts"])


def _tones() -> tuple[str, ...]:
    return tuple(k for k in load()["colors"]["about"])


FONTS: tuple[str, ...] = _fonts()
TONES: tuple[str, ...] = _tones()


def font(role: str) -> dict:
    return dict(load()["fonts"][role])


def style(role: str, look: str) -> str:
    """The design system's type style a font role wears in a look (`camp` or `office`)."""
    return load()["gui"]["fonts"][role][look]


def color(role: str, theme: str) -> str:
    return load()["colors"][theme][role]


def css_var(tone: str) -> str:
    """The design system's colour token of a colour role, as a CSS variable (`fire` → `--alert`)."""
    return "--" + load()["gui"]["colors"][tone]


UPPERCASE = ("camp-label", "office-heading")     # tokens.json says so in their usage, not as a field


def _css_class(name: str) -> str:
    return name.replace(".", "-").replace("_", "-")


def roles_css() -> str:
    """The CSS of the roles a UI document names: `.ok-font-<role>` per look and `.ok-tone-<role>`, all
    read from the design system's tokens, so a pane never carries a value of its own."""
    styles, lines = _styles(), ["/* Generated by orkcraft.design.tokens.roles_css() from design-system/tokens.json. */"]
    looks = {"camp": ':root, [data-theme^="camp"]', "office": '[data-theme="office"]'}
    for look, scope in looks.items():
        for role in FONTS:
            st = styles[style(role, look)]
            decl = [f"font-family: var(--font-{st['family']})", f"font-size: {st['fontSize']}",
                    f"line-height: {st['lineHeight']}", f"font-weight: {st['fontWeight']}"]
            # Every declaration is written in both looks, so Office never inherits Camp's.
            decl.append(f"letter-spacing: {st.get('letterSpacing') or 'normal'}")
            upper = st.get("textTransform") == "uppercase" or st["name"] in UPPERCASE
            decl.append(f"text-transform: {'uppercase' if upper else 'none'}")
            decl.append(f"font-variant-numeric: {'tabular-nums' if st['name'] == 'camp-number' else 'normal'}")
            selector = ", ".join(f"{s.strip()} .ok-font-{role}" for s in scope.split(","))
            lines.append(f"{selector} {{ {'; '.join(decl)}; }}")
    for tone in TONES:
        lines.append(f".ok-tone-{_css_class(tone)} {{ color: var({css_var(tone)}); }}")
    return "\n".join(lines) + "\n"


def space(step: int, unit: str = "px") -> int:
    steps = load()["space"][unit]
    return steps[max(0, min(step, len(steps) - 1))]


def problems() -> list[str]:
    """What is wrong with tokens.json itself: every theme has every colour role, every font names a
    family every theme has. (The tests run it; a hand edit of the file is checked the same way.)"""
    data, out = load(), []
    for theme in THEMES:
        missing = set(TONES) - set(data["colors"].get(theme, {}))
        if missing:
            out.append(f"colors.{theme}: no {sorted(missing)}")
    # The GUI's map onto the design system: every role has a style and a colour token there.
    gui, styles = data["gui"], _styles()
    colours = {c["name"] for c in system()["color"]["tokens"]}
    for role in FONTS:
        for look in THEMES:
            name = gui["fonts"].get(role, {}).get(look)
            if name not in styles:
                out.append(f"gui.fonts.{role}.{look}: no type style {name!r} in design-system/tokens.json")
    for tone in TONES:
        if gui["colors"].get(tone) not in colours:
            out.append(f"gui.colors.{tone}: no colour token {gui['colors'].get(tone)!r} in design-system/tokens.json")
    return out
