# (id, product building, title, rtsAnalog, text lines, dogma, why chosen, screenshot plan)
SEL = {
"peon": [
 ("task-fields", "fields", "Task Fields", "build queue",
  ["Three columns: to do, in work, done.", "Pull 'Review auth refresh PR' into work,", "and an orc picks it up."],
  "Play, not toil", "Where every engineering day starts: the queue agents take work from.",
  "Board: T2101 PKCE exchange in progress, T2102 refresh reuse blocked by it, done column with merged work."),
 ("barracks", "barracks", "Barracks", "unit production / control groups",
  ["Three orcs, three git worktrees, one queue.", "A follow-up goes to the orc that wrote the first part.", "The foreman says why it hired whom."],
  "No micromanagement", "Parallel agents without stepping on each other's branches is the core dev win.",
  "Orcs Grub/Mogka style rows renamed to on-brand: Smith on feat/oauth-flow ✓3, Tinker failed ✗1, queue: 'Docs for the token API'."),
 ("forge", "forge", "The Forge", "upgrade gate",
  ["Branches with their PRs and changes.", "Tests run in a throw-away worktree first;", "red means no merge, green squash-merges."],
  "Hard knocks teach", "Closes the loop: tests -> merge, the step agents most often get wrong.",
  "feat/oauth-flow PR #41, tests 1 failing, gate CLOSED; fix/token-ttl green, ready to merge."),
 ("lake-of-insight", "lake", "Lake of Insight", "unit inspection panel",
  ["Review the agent's diff side by side,", "not as a wall of chat:", "auth/token.py on feat/oauth, before | after."],
  "Less text", "Code review is where an engineer's attention goes; this is the review screen.",
  "Side-by-side diff of exchange_code() in the OAuth worktree."),
 ("orc-council", "council", "Orc Council", "war council",
  ["Diff Inspector and Test Runner review the patch.", "An objection sends it back: round 3 of 4,", "with a hard cap on rounds and dollars."],
  "Hard knocks teach", "Agent-on-agent review before a human looks; failed work is sent back.",
  "The R1/R2 objection rounds (same data as prev-review-sendback)."),
 ("watchtower", "watchtower", "Watchtower", "early-warning tower",
  ["Watches GitHub for you: a PR opened,", "a review requested, a check failed.", "Each event rolls down a road to whoever handles it."],
  "No micromanagement", "CI and PR events trigger work without you polling tabs.",
  "Event feed: PR #41 review requested, check 'unit' failed on feat/oauth-flow, cron 09:00 triage."),
 ("loot-vault", "loot", "Loot Vault", "loot stash",
  ["What the agents wrote, waiting for a yes:", "CHANGELOG for v0.9.0, release notes.", "Accept it, or roll it back."],
  "Hard knocks teach", "Release step: generated changelog and notes, with what each cost.",
  "Files: CHANGELOG.md +14, docs/release-v0.9.0.md, cost per file."),
 ("tally-crag", "crag", "Tally Crag", "resource counter",
  ["Tokens per building over the last 24 h.", "The Forge ate 174k; the Lake 77k.", "A bar turns red past the limit you set."],
  "Count the lumber", "Engineers pay for agent runs; this shows which step burns tokens.",
  "Horizontal token bars per building (the earlier Tally Crag shot)."),
],
"knight": [
 ("launch-board", "fields", "Launch Board", "build queue",
  ["Code, copy and launch on one board:", "'Stripe webhooks', 'Launch post and pricing page',", "'Fix checkout 500'. Nothing lives in your head."],
  "Play, not toil", "A one-person team needs one list for code, copy and ops.",
  "Columns: Stripe billing in progress, Launch post + pricing page todo, checkout 500 bug blocked."),
 ("barracks", "barracks", "Barracks", "unit production",
  ["While you write the launch post,", "two orcs take Stripe webhooks and the 500 fix,", "each in its own worktree. Hard cap: $5."],
  "No micromanagement", "The founder's biggest lever: agents code while they do everything else.",
  "Smith on feat/stripe-billing working, Scout on fix/checkout-500, budget $1.84/5."),
 ("tally-crag", "crag", "Tally Crag", "resource counter",
  ["Your own money, per building:", "Barracks $2.20, Forge $0.90 today.", "Yellow at the warn line, red at the cap."],
  "Count the lumber", "Solo founders pay out of pocket; spend has to be visible.",
  "Spend bars ($) per building, one over warn."),
 ("watchtower", "watchtower", "Watchtower", "early-warning tower",
  ["After the deploy it keeps watch:", "a Sentry alert mail, a refund request,", "a failed check. You get the cart, not the noise."],
  "No micromanagement", "Nobody else is on call; the tower is.",
  "Feed: deploy v1.8.0, checkout 500 (StripeInvalidRequest), mail 'Refund request'."),
 ("forge", "forge", "The Forge", "upgrade gate",
  ["feat/stripe: PR #12 open, +413 −3.", "One key tests it and squash-merges it into main.", "Red tests keep the gate shut."],
  "Hard knocks teach", "Shipping safely without a reviewer to catch you.",
  "Two branches: stripe-billing green/ready, checkout fix red."),
 ("loot-vault", "loot", "Loot Vault", "loot stash",
  ["The launch post, HN and Product Hunt drafts,", "the pricing page copy: read it, accept it,", "or roll it back."],
  "Hard knocks teach", "Copy and launch assets are half a founder's output.",
  "Files: launch-post.md, ph-draft.md, pricing.md with costs."),
 ("town-hall", "town_hall", "Town Hall", "base building / tech tree",
  ["Say what you need: 'post every merged PR to the changelog'.", "The Builder plans it; you approve before anything stands.", "Z undoes any building."],
  "Play, not toil", "No time to wire tools; describe the building and get it.",
  "Town Hall: Council verdicts, proposals, spend line."),
 ("catapult", "catapult", "The Catapult", "launch siege engine",
  ["Waits for the build, the notes and the board,", "checks them against a schema,", "then fires the release to your webhook."],
  "Play, not toil", "Launch day: one strict exit instead of copy-pasting into three tools.",
  "Catapult: 3 inputs ready, schema ✓, target example.com hook, Dry run / Fire."),
],
"elf": [
 ("loot-vault", "loot", "Loot Vault", "loot stash",
  ["'Hero section, 3 variants' land as files.", "Approve hero-b, roll back a and c.", "Nothing reaches the repo without your yes."],
  "Hard knocks teach", "Asset approval is the designer's gate on agent output.",
  "Three hero variant files + an icon set, one accepted, two pending."),
 ("lake-of-insight", "lake", "Lake of Insight", "scouting lens",
  ["Two versions of the error copy, side by side:", "'Something went wrong' or 'We couldn't", "reach your bank'. Pick one, no doc ping-pong."],
  "Less text", "Looking at the thing, not reading about it.",
  "ASCII wireframe of 'Connect bank' error state (design_review demo)."),
 ("orc-council", "council", "Orc Council", "war council",
  ["A Critic, an Accessibility orc and a Copy orc", "critique the onboarding flow until they agree.", "Objections come back as a list, round by round."],
  "Hard knocks teach", "Critique comments without waiting for the Thursday review.",
  "Rounds: Accessibility objects (focus order), Copy objects, round 2 agrees."),
 ("token-mill", "mill", "Token Mill", "refinery",
  ["Design tokens JSON in, CSS variables out.", "Regexes and templates, no model,", "so rebuilding the tokens costs nothing."],
  "Count the lumber", "Token pipelines are deterministic; they should not burn a model.",
  "Mill steps: tokens.json -> css vars, 64 tokens done, $0."),
 ("the-pit", "pit", "The Pit", "resource drop-off",
  ["Drop screenshots, paste a moodboard link", "or a client note. No dialog, no form:", "the Scavenger sorts it to the right building."],
  "Play, not toil", "Where references and feedback enter without ceremony.",
  "Pit: three dropped files + a pasted link, routed to Lake / Task Fields."),
 ("task-fields", "fields", "Task Fields", "build queue",
  ["Every screen through its states:", "'Onboarding step 2: empty, loading, error'.", "Done only when all four are."],
  "Play, not toil", "Design work is tracked per screen and state.",
  "Board with the design_review onboarding tasks."),
 ("scroll-dump", "scrolls", "Scroll Dump", "lore library",
  ["Your design guidelines and component notes.", "Agents get only the fragment they need,", "and personal notes never reach a model."],
  "Count the lumber", "Keeps agents on the design system without pasting it into every prompt.",
  "Scrolls: Buttons.md, Spacing.md, Voice & tone; fragment picked for a prompt."),
 ("forge", "forge", "The Forge", "upgrade gate",
  ["Hand off chore/tokens-v2 as PR #7:", "the tests run first,", "then one key squash-merges it."],
  "Hard knocks teach", "Handoff to engineering without a ticket ping-pong.",
  "chore/tokens-v2 branch, Style Dictionary build ✓, ready to merge."),
],
"lich": [
 ("sprint-board", "fields", "Sprint Board", "build queue",
  ["Sprint 14 at a glance: 9 to do, 4 in work,", "6 done. 'Security review OAuth' sits", "where everyone can see it."],
  "Less text", "Statuses without a standup.",
  "Board: Sprint 14 tasks with a blocked chain."),
 ("loot-vault", "loot", "Loot Vault", "loot stash",
  ["'Sprint 14 status digest' arrives every morning", "as a report: 6 events, 2 blockers.", "Kept with when it came and what it cost."],
  "Less text", "The daily digest is the manager's main read.",
  "Reports: digest week 40, release notes, each with cost."),
 ("tally-crag", "crag", "Tally Crag", "resource counter",
  ["Sprint 14 in bars: 9 to do, 4 in work, 6 done.", "One key flips it to spend or runs,", "with a warn line and a cap you set."],
  "Count the lumber", "Metrics and spend in one place.",
  "Tasks-per-column bars or spend bars per orkspace."),
 ("watchtower", "watchtower", "Watchtower", "early-warning tower",
  ["Watches GitHub, mail and the schedule:", "'#41 review waiting 2 days'", "lands here, not in a lost thread."],
  "No micromanagement", "Escalations come to you instead of you hunting them.",
  "Health Radar feed (delivery_control demo)."),
 ("war-drum", "war_drum", "War Drum", "turn timer",
  ["Your calendar as the day's rhythm:", "10:00 standup, 14:00 Sprint 14 review.", "What is now and what is next, nothing else."],
  "Less text", "A coordinator's day is its meetings.",
  "Today: Standup now, 1:1 next, Sprint 14 review 15:00."),
 ("orc-council", "council", "Orc Council", "war council",
  ["Planner, Critic and Security agree on", "the Sprint 15 plan before you read it:", "11 stories cut to 8. Max 3 rounds, max $2."],
  "Hard knocks teach", "Plans get stress-tested before they reach a meeting.",
  "Council: release/sprint plan, agreed in round 2."),
 ("barracks", "barracks", "Barracks", "unit production",
  ["Who works on what right now:", "two orcs busy, one task waiting.", "Every assignment comes with its reason."],
  "No micromanagement", "Oversight of agent work without assigning each task.",
  "Barracks: orcs, queue, foreman's decisions."),
 ("scroll-dump", "scrolls", "Scroll Dump", "lore library",
  ["Meeting notes, decisions, ADRs in one place.", "Agents quote the decision, not the whole wiki.", "1:1 notes stay personal."],
  "Count the lumber", "Decisions need to be findable by people and agents.",
  "Scrolls: ADR-014, 1:1 prep, retro notes."),
],
}
LEFT_OUT = {
"peon": "Pit (intake is not where an engineer's day goes), Totem and Mill (plumbing between buildings, not daily work), Horn (sound alerts duplicate Watchtower), War Drum (meetings), File Forest (the editor does this better), Scroll Dump (useful but secondary), Catapult (outbound APIs are rare for dev work), Town Hall and Workshop (setting up the town, not daily work).",
"knight": "Pit, Totem and Mill (plumbing), Lake of Insight (review matters less with no team; the Forge's tests are the gate), Orc Council (debate is a luxury solo), Horn and War Drum (nice, not core), File Forest and Scroll Dump (secondary), Workshop (covered by Town Hall).",
"elf": "Barracks, Watchtower and Catapult (engineering and ops), Tally Crag (designers rarely own budget), Totem (plumbing), War Drum and Horn (nice, not core), File Forest (repo browsing), Town Hall and Workshop (setup). Note: the terminal shows mockups as ASCII wireframes, Markdown and file lists, not rendered images.",
"lich": "Pit, Totem, Mill and Catapult (plumbing), Lake of Insight and Forge (code-level), File Forest (repo browsing), Horn (alert sound only), Town Hall and Workshop (setup; Town Hall's weekly audit is close to making the list).",
}
